# Generated by Django 4.2.5 on 2023-09-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('emoname', models.CharField(max_length=20)),
                ('empaddres', models.CharField(max_length=100)),
                ('empsalary', models.IntegerField()),
            ],
        ),
    ]
